// File generated by FlutterFire CLI.
// This file contains the Firebase options for your web application.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Configuración de Firebase con manejo seguro de credenciales
/// Para usar este archivo:
/// 1. Cópialo a firebase_options.dart
/// 2. Asegúrate de tener un archivo .env con las variables necesarias
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Add other platforms here if needed
    throw UnsupportedError(
      'DefaultFirebaseOptions are only supported for web.',
    );
  }

  /// Acceso seguro a las variables de entorno
  /// Utilizamos el operador ?? para proporcionar un valor predeterminado
  /// en caso de que la variable no esté definida
  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _getEnvOrEmpty('FIREBASE_API_KEY'),
    appId: _getEnvOrEmpty('FIREBASE_APP_ID'),
    messagingSenderId: _getEnvOrEmpty('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvOrEmpty('FIREBASE_PROJECT_ID'),
    authDomain: _getEnvOrEmpty('FIREBASE_AUTH_DOMAIN'),
    storageBucket: _getEnvOrEmpty('FIREBASE_STORAGE_BUCKET'),
    measurementId: _getEnvOrEmpty('FIREBASE_MEASUREMENT_ID'),
  );
  
  /// Método auxiliar para obtener variables de entorno de forma segura
  /// Devuelve un string vacío si la variable no está definida
  static String _getEnvOrEmpty(String key) {
    final value = dotenv.env[key];
    if (value == null || value.isEmpty) {
      print('WARNING: Variable de entorno $key no encontrada o vacía');
      return '';
    }
    return value;
  }
}